/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateIndexRouteImport } from './routes/create/index'
import { Route as UserIdIndexRouteImport } from './routes/$userId/index'
import { Route as UserIdEditRouteImport } from './routes/$userId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdIndexRoute = UserIdIndexRouteImport.update({
  id: '/$userId/',
  path: '/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdEditRoute = UserIdEditRouteImport.update({
  id: '/$userId/edit',
  path: '/$userId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$userId/edit': typeof UserIdEditRoute
  '/$userId': typeof UserIdIndexRoute
  '/create': typeof CreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$userId/edit': typeof UserIdEditRoute
  '/$userId': typeof UserIdIndexRoute
  '/create': typeof CreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$userId/edit': typeof UserIdEditRoute
  '/$userId/': typeof UserIdIndexRoute
  '/create/': typeof CreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$userId/edit' | '/$userId' | '/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$userId/edit' | '/$userId' | '/create'
  id: '__root__' | '/' | '/$userId/edit' | '/$userId/' | '/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserIdEditRoute: typeof UserIdEditRoute
  UserIdIndexRoute: typeof UserIdIndexRoute
  CreateIndexRoute: typeof CreateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$userId/': {
      id: '/$userId/'
      path: '/$userId'
      fullPath: '/$userId'
      preLoaderRoute: typeof UserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$userId/edit': {
      id: '/$userId/edit'
      path: '/$userId/edit'
      fullPath: '/$userId/edit'
      preLoaderRoute: typeof UserIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserIdEditRoute: UserIdEditRoute,
  UserIdIndexRoute: UserIdIndexRoute,
  CreateIndexRoute: CreateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
